ktor:
    application:
        modules:
            - com.ApplicationKt.module
    deployment:
        port: 8080


database:
    url: $dbUrl
    user: $dbUser
    password: $dbPassword

jwt:
    secret: $jwtSecret
    issuer: $jwtIssuer
    audience: finances-service
    realm: Access to Finances Ktor
